# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://vincenthawk.github.io'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: '/dendentech-site' 

# Title of the Site
title: 登登科技
# Description of the Site
description: 用科技開創未來，用心靈服務社會。
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /favicon.ico

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://vincenthawk.github.io/dendentech-site/assets/images/cover.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: thedevslot@gmail.com
facebook_username: thedevslot
twitter_username: thedevslot
instagram_username: thedevslot
linkedin_username: thedevslot
github_username:  thedevslot
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: TheDevsLot
# URL for the Image of the Author
author-image: https://vincenthawk.github.io/dendentech-site/assets/images/Den_logo.png
# 60 Words About the Author
author-about: 創業家掃地僧＋資深唱片/遊戲製作人+全能AI/錄音工程師因緣際會共創的新創公司，目標用新科技與創意顛覆傳統，帶動新的風潮。
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
